FROM python:3.12-slim AS builder

WORKDIR /app

# Установка poetry
COPY pyproject.toml poetry.lock /app/
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-dev

# Этап 2: сборка финального образа
FROM python:3.12-slim

WORKDIR /app

# Копирование установленных зависимостей из предыдущего этапа
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin/poetry /usr/local/bin/poetry

# Копирование исходного кода
COPY . /app

# Установка Uvicorn без сохранения кеша
RUN pip install --no-cache-dir uvicorn

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8005"]