version: '3.9'

services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    image: enji_copilot_fastapi
    container_name: fastapi_container
    command: uvicorn main:app --host 0.0.0.0 --port 8005
    ports:
      - "8005:8005"
    # depends_on:
    #   - pgvector
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65536
        hard: 65536


  # pgvector:
  #   image: pgvector/pgvector:pg15
  #   container_name: pgvector
  #   ports:
  #     - "5439:5432"
  #   environment:
  #     - POSTGRES_DB=vectordb
  #     - POSTGRES_USER=testuser
  #     - POSTGRES_PASSWORD=testpwd
  #   networks:
  #     - backend

  redis:
    # restart: always
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  celery_worker:
    build:
      context: ./
    image: enji_copilot_fastapi
    container_name: celery_worker
    working_dir: /app
    command: celery -A celery_worker worker -l info
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis

  celery_beat:
    build:
      context: ./
    image: enji_copilot_fastapi
    container_name: celery_beat
    working_dir: /app
    command: celery -A celery_worker beat -l info
    volumes:
      - .:/app
    networks:
      - backend
    depends_on:
      - redis


networks:
  backend:
    driver: bridge

volumes:
  chromadb_data:
    driver: local
